"use client";
import Link from "next/link";
import {useRef,useState} from "react";
import {services} from "@/content/site";
import {MediaPlaceholder} from "./media-placeholder";
import {useMotion} from "./site-experience";
export function ServiceCarousel({standalone=false}:{standalone?:boolean}){
const [active,setActive]=useState(1);const pointerStart=useRef<number|null>(null);const {paused}=useMotion();const change=(direction:number)=>setActive(index=>Math.max(0,Math.min(services.length-1,index+direction)));
return <section className={`services-section ${standalone?"services-standalone":""}`} aria-label="Services">{!standalone&&<h2 className="section-title">Services we offer</h2>}<div className="carousel-window" role="region" aria-roledescription="carousel" aria-label="Explore our services" onKeyDown={event=>{if(event.key==="ArrowRight"||event.key==="ArrowLeft"){event.preventDefault();change(event.key==="ArrowRight"?1:-1);}}}><div className="carousel-track" style={{transform:`translateX(calc(50% - var(--service-card-width) / 2 - ${active} * (var(--service-card-width) + var(--service-gap))))`,transitionDuration:paused?"0ms":undefined}} onPointerDown={event=>{pointerStart.current=event.clientX;}} onPointerUp={event=>{if(pointerStart.current!==null&&Math.abs(event.clientX-pointerStart.current)>55)change(event.clientX<pointerStart.current?1:-1);pointerStart.current=null;}} onPointerCancel={()=>{pointerStart.current=null;}}>{services.map((service,index)=><article key={service.slug} className={`service-card ${index===active?"is-active":""}`} aria-label={`${index+1} of ${services.length}: ${service.title}`}><button className="service-select" onClick={()=>setActive(index)} aria-label={`Show ${service.title}`} tabIndex={index===active?-1:0} disabled={index===active}/><h3>{service.title}</h3><p>{service.line}</p><MediaPlaceholder kind="foto" label={service.title}/><Link href={`/services/${service.slug}`} className="service-link" tabIndex={index===active?0:-1}>Learn more <span aria-hidden="true">↗</span></Link></article>)}</div></div><div className="carousel-controls"><button type="button" className="round-button" aria-label="Previous service" onClick={()=>change(-1)} disabled={active===0}>←</button><div className="carousel-dots">{services.map((service,index)=><button key={service.slug} onClick={()=>setActive(index)} aria-label={`Go to ${service.title}`} aria-pressed={active===index}><span/></button>)}</div><button type="button" className="round-button" aria-label="Next service" onClick={()=>change(1)} disabled={active===services.length-1}>→</button></div><p className="sr-only" aria-live="polite">{(services[active]??services[0]).title}, {active+1} of {services.length}</p></section>;
}
